
name: Build Pake App

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux packages
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install Pake
        run: pnpm install -g pake-cli

      - name: Build app
        run: pake https://your-app-url.com/subfolder --name "My App"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pake-${{ matrix.os }}
          path: |
            **/dist/**
            **/target/release/bundle/**
